apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pvc-pod
spec:
  containers:
  - name: pv-container
    image: nginx
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: task-pv-storage
      mountPath: /pvcclaimedvol1
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  restartPolicy: Always