apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      #env: prod
  template:
    metadata:
      labels:
        app: nginx
        env: prod #will be used for service binding
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello #latest #<<<nginx:1.16.1<<< #nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: democlusterip
  namespace: default
spec:
  selector:
    env: prod
  type: ClusterIP
  ports:
  - name: demosport
    protocol: TCP
    port: 8191 #clusterip port
    targetPort: 80